version: '3.8'

services:
  sql1:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql1
    hostname: sql1
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=<YourStrong@Passw0rd>
    ports:
      - "1433:1433"
    volumes:
      - sql1data:/var/opt/mssql
    networks:
      - sqlnet

volumes:
  sql1data:

networks:
  sqlnet:
    driver: bridge